### ISSUE TITLE
Redesign the data model

### ISSUE THREAD

**Issue by 4rgc** [4rgc/trellzo-backend#8]
## Description

The current schema is overusing data embedding due to the lack of the designer's understanding of the possible bugs, undesired consequences, and scalability problems with this approach. 

Instead, the schema should separate the objects' collections based on application specifics (how they're used).

### Example

- Boards can be retrieved or mutated by many users –> **they should be separated**
- Lists can only exist within one board, and only have very few properties –> **they can be embedded into the board**

**Comment by ctrldrift** [comment]
this might be closed already? 
BTW, you can link your issues to the PR's/commits as a #10

**Comment by 4rgc** [comment]
Indeed, closed with #10
